### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dylanhamada** [dylanhamada/graph-it#1]
- [ ] Complete HTML Canvas Tutorial
- [ ] Complete features list and basic functionality
- [ ] Mock up design on Figma
- [ ] Begin building
